name: Deploy GCP Function with WIF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: "projects/31239933098/locations/global/workloadIdentityPools/github-pool/providers/github-provider2"
        service_account: "github-actions@guido-460817.iam.gserviceaccount.com"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy notify_email \
          --runtime python310 \
          --trigger-topic my-topic \
          --entry-point notify_email \
          --source . \
          --region=us-central1 \
          --set-env-vars "username=${{ secrets.EMAIL_USERNAME }},password=${{ secrets.EMAIL_PASSWORD }},sender=${{ secrets.EMAIL_SENDER }},recipients=${{ secrets.EMAIL_RECIPIENTS }},SMTP=smtp.gmail.com"
